# Day 6: Functions, While loop and IndentationError
# Functions are block of code have specific functions and are initialized by calling them 
# Indentation in python is just like the curly braces of most languages they are reffered to scopes
# Unlike the for loop the while loop is used with a boolean statement 
# while for loops iterates over sequences, fWhile loops iterates over a condition
# Project Name: guessing game
from random import randint
def guessing_game():
    print("Welcome to this pyguessing game!\nIn this game the goal is to guess the random number generated by the computer in n amount of tries.")
    print("The number ranges from 0-4")
    random_number = randint(0,5)
    user_number = 0
    while user_number != random_number:
        user_number = int(input("Pick a number: "))
        if user_number == random_number:
            print("Hurray!!! you guessed the number")
        else:
            print("Wrong guess....go again!!")


guessing_game()